/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SellCarRouteImport } from './routes/sell-car'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CarSlugRouteImport } from './routes/car.$slug'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminResetPasswordRouteImport } from './routes/admin.reset-password'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin.forgot-password'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCarsIndexRouteImport } from './routes/admin.cars.index'
import { Route as AdminCarsNewRouteImport } from './routes/admin.cars.new'
import { Route as AdminCarsEditIdRouteImport } from './routes/admin.cars.edit.$id'

const SellCarRoute = SellCarRouteImport.update({
  id: '/sell-car',
  path: '/sell-car',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const CarSlugRoute = CarSlugRouteImport.update({
  id: '/car/$slug',
  path: '/car/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarsIndexRoute = AdminCarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarsNewRoute = AdminCarsNewRouteImport.update({
  id: '/cars/new',
  path: '/cars/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarsEditIdRoute = AdminCarsEditIdRouteImport.update({
  id: '/cars/edit/$id',
  path: '/cars/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/inventory': typeof InventoryRoute
  '/sell-car': typeof SellCarRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/car/$slug': typeof CarSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cars/new': typeof AdminCarsNewRoute
  '/admin/cars/': typeof AdminCarsIndexRoute
  '/admin/cars/edit/$id': typeof AdminCarsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/inventory': typeof InventoryRoute
  '/sell-car': typeof SellCarRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/car/$slug': typeof CarSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/cars/new': typeof AdminCarsNewRoute
  '/admin/cars': typeof AdminCarsIndexRoute
  '/admin/cars/edit/$id': typeof AdminCarsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/inventory': typeof InventoryRoute
  '/sell-car': typeof SellCarRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/car/$slug': typeof CarSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cars/new': typeof AdminCarsNewRoute
  '/admin/cars/': typeof AdminCarsIndexRoute
  '/admin/cars/edit/$id': typeof AdminCarsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/inventory'
    | '/sell-car'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/media'
    | '/admin/reset-password'
    | '/admin/seo'
    | '/admin/settings'
    | '/car/$slug'
    | '/admin/'
    | '/admin/cars/new'
    | '/admin/cars/'
    | '/admin/cars/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/inventory'
    | '/sell-car'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/media'
    | '/admin/reset-password'
    | '/admin/seo'
    | '/admin/settings'
    | '/car/$slug'
    | '/admin'
    | '/admin/cars/new'
    | '/admin/cars'
    | '/admin/cars/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/inventory'
    | '/sell-car'
    | '/admin/customers'
    | '/admin/dashboard'
    | '/admin/forgot-password'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/media'
    | '/admin/reset-password'
    | '/admin/seo'
    | '/admin/settings'
    | '/car/$slug'
    | '/admin/'
    | '/admin/cars/new'
    | '/admin/cars/'
    | '/admin/cars/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  InventoryRoute: typeof InventoryRoute
  SellCarRoute: typeof SellCarRoute
  CarSlugRoute: typeof CarSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sell-car': {
      id: '/sell-car'
      path: '/sell-car'
      fullPath: '/sell-car'
      preLoaderRoute: typeof SellCarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/car/$slug': {
      id: '/car/$slug'
      path: '/car/$slug'
      fullPath: '/car/$slug'
      preLoaderRoute: typeof CarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cars/': {
      id: '/admin/cars/'
      path: '/cars'
      fullPath: '/admin/cars/'
      preLoaderRoute: typeof AdminCarsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cars/new': {
      id: '/admin/cars/new'
      path: '/cars/new'
      fullPath: '/admin/cars/new'
      preLoaderRoute: typeof AdminCarsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cars/edit/$id': {
      id: '/admin/cars/edit/$id'
      path: '/cars/edit/$id'
      fullPath: '/admin/cars/edit/$id'
      preLoaderRoute: typeof AdminCarsEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCarsNewRoute: typeof AdminCarsNewRoute
  AdminCarsIndexRoute: typeof AdminCarsIndexRoute
  AdminCarsEditIdRoute: typeof AdminCarsEditIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCarsNewRoute: AdminCarsNewRoute,
  AdminCarsIndexRoute: AdminCarsIndexRoute,
  AdminCarsEditIdRoute: AdminCarsEditIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  InventoryRoute: InventoryRoute,
  SellCarRoute: SellCarRoute,
  CarSlugRoute: CarSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
